name: Update IP List

on:
  schedule:
    - cron: "0 */12 * * *" # 每 12 小时运行一次
  workflow_dispatch: # 允许手动触发

jobs:
  update-ip:
    runs-on: ubuntu-latest

    steps:
      # 检出代码库
      - name: Checkout repository
        uses: actions/checkout@v3

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # 替换为你的 Python 版本

      # 安装依赖
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # 运行脚本
      - name: Run script
        run: |
          python collect_ips.py

      # 提交并推送更改
      - name: Commit and Push changes
        run: |
          git config --global user.name "Your GitHub Username"
          git config --global user.email "Your GitHub Email"
          git add ip.txt
          git commit -m "Automated update of IP list"
          git push origin main
