name: Update Cloudflare DNS

on:
  schedule:
    - cron: '*/30 * * * *'  # 每隔三十分钟运行一次
  workflow_dispatch:  # 手动触发
  # push: # 如果你想提交时也触发，可以取消注释

jobs:
  update-dns:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run update script
      env:
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      run: |
        run: |
  python bestdomain.py --domains 38806827.xyz --proxied true
